/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/HeFei/BaseChart.vue')['default']
    BlockHeader: typeof import('./src/components/HeFei/BlockHeader.vue')['default']
    DeviceChart: typeof import('./src/components/HeFei/MonitorChart/DeviceChart.vue')['default']
    DeviceMonitor: typeof import('./src/components/HeFei/DeviceMonitor.vue')['default']
    DisasterClassificationStatistics: typeof import('./src/components/HeFei/DisasterClassificationStatistics/index.vue')['default']
    DiskChart: typeof import('./src/components/HeFei/MonitorChart/DiskChart.vue')['default']
    DiskMonitor: typeof import('./src/components/HeFei/DiskMonitor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HardDoughnut: typeof import('./src/components/hardmoni/HardDoughnut.vue')['default']
    Index: typeof import('./src/components/HorScroll/Index.vue')['default']
    IndexV3: typeof import('./src/components/HorScroll/IndexV3.vue')['default']
    LabelSelect: typeof import('./src/components/HeFei/LabelSelect.vue')['default']
    MapBorder: typeof import('./src/components/company/mapBorder.vue')['default']
    RadarProduct: typeof import('./src/components/HeFei/RadarProduct.vue')['default']
    RealElement: typeof import('./src/components/HeFei/RealElement.vue')['default']
    RealWarning: typeof import('./src/components/HeFei/RealWarning.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenShot: typeof import('./src/components/ScreenShot/index.vue')['default']
    ServerBlock: typeof import('./src/components/hardmoni/ServerBlock.vue')['default']
    SevenForecast: typeof import('./src/components/HeFei/SevenForecast.vue')['default']
    StationMonitor: typeof import('./src/components/HeFei/StationMonitor.vue')['default']
    ThreeForecast: typeof import('./src/components/HeFei/ThreeForecast.vue')['default']
    TimeLine: typeof import('./src/components/company/TimeLine.vue')['default']
    Toolbar: typeof import('./src/components/ScreenShot/Toolbar/index.vue')['default']
    WarningStatistic: typeof import('./src/components/HeFei/WarningStatistic/index.vue')['default']
    WarningStatistics: typeof import('./src/components/HeFei/WarningStatistics.vue')['default']
  }
}
